
POST http://localhost:8080/api/chirps
content-type: application/json

{
    "body": "HELLO MY FRIEND!"
}

###

POST http://localhost:8080/api/chirps
content-type: application/json

{
    "body": "HELLO MY FRIEND!HELLO MY FRIEND!HELLO MY FRIEND!HELLO MY FRIEND!HELLO MY FRIEND!HELLO MY FRIEND!HELLO MY FRIEND!HELLO MY FRIEND!HELLO MY FRIEND!HELLO MY FRIEND!HELLO MY FRIEND!HELLO MY FRIEND!HELLO MY FRIEND!HELLO MY FRIEND!HELLO MY FRIEND!HELLO MY FRIEND!"
}

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "orielbaz1@gmail.com",
    "password": "poop"
}

###

POST http://localhost:8080/admin/reset
Content-Type: application/json


###

GET http://localhost:8080/api/chirps